build_from:
  amd64: ghcr.io/home-assistant/amd64-base:latest
  aarch64: ghcr.io/home-assistant/aarch64-base:latest

labels:
  org.opencontainers.image.title: "SwampTimers"
  org.opencontainers.image.description: "Advanced timer scheduling for Home Assistant"
  org.opencontainers.image.source: "https://github.com/jaimemahaffey/swamptimers"
  org.opencontainers.image.licenses: "MIT"

args:
  BUILD_VERSION: "1.0.4"
