build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  amd64: ghcr.io/home-assistant/amd64-base:latest
  armhf: ghcr.io/home-assistant/armhf-base:latest
  armv7: ghcr.io/home-assistant/armv7-base:latest
  i386: ghcr.io/home-assistant/i386-base:latest

labels:
  org.opencontainers.image.title: "SwampTimers"
  org.opencontainers.image.description: "Advanced timer scheduling for Home Assistant"
  org.opencontainers.image.source: "https://github.com/yourusername/swamptimers"
  org.opencontainers.image.licenses: "MIT"

args:
  BUILD_VERSION: "1.0.0"
